<a href="https://colab.research.google.com/github/SaimNaveed646/CardiovasularDiseasePrediction/blob/main/CardioDiseasePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
import pandas as pd

In [78]:
data = pd.read_csv("https://raw.githubusercontent.com/SaimNaveed646/CardiovasularDiseasePrediction/main/cardio_train.csv", sep=";", header=0)

In [79]:
data.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [80]:
data.shape

(70000, 13)

In [81]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [82]:
data.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,19468.865814,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,2467.251667,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,10798.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,17664.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,19703.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,21327.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

# **Cleaning**

In [83]:
data['id'].duplicated().sum()

np.int64(0)

In [84]:
data.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [85]:
data['age'] = data['age'] / 365

In [86]:
data['height'] = data['height'] / 100

In [87]:
data = data[
    (data['ap_hi'] >= 50) &
    (data['ap_hi'] <= 250) &
    (data['ap_lo'] >= 40) &
    (data['ap_lo'] <= 200) &
    (data['ap_hi'] > data['ap_lo'])
]

In [88]:
data.shape

(68672, 13)

# **Feature Engneering**

In [89]:
data['bmi'] = data['weight'] / (data['height'] ** 2)

In [90]:
data['pulse_pressure'] = data['ap_hi'] - data['ap_lo']

In [91]:
data['lifestyle_risk'] = data['smoke'] + data['alco'] - data['active']

In [92]:
data.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio,bmi,pulse_pressure,lifestyle_risk
0,0,50.391781,2,1.68,62.0,110,80,1,1,0,0,1,0,21.967120,30,-1
1,1,55.419178,1,1.56,85.0,140,90,3,1,0,0,1,1,34.927679,50,-1
2,2,51.663014,1,1.65,64.0,130,70,3,1,0,0,0,1,23.507805,60,0
3,3,48.282192,2,1.69,82.0,150,100,1,1,0,0,1,1,28.710479,50,-1
4,4,47.873973,1,1.56,56.0,100,60,1,1,0,0,0,0,23.011177,40,0

# **Feature Scaling**

In [93]:
cols_to_drop = ["id"]

df_model1 = data.drop(columns=cols_to_drop)

In [94]:
X = df_model1.drop("cardio", axis=1)
y = df_model1["cardio"]

In [95]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [96]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [97]:
import pandas as pd

X_train = pd.DataFrame(X_train, columns=X.columns)
X_test = pd.DataFrame(X_test, columns=X.columns)

In [98]:
X_train.head()

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,bmi,pulse_pressure,lifestyle_risk
0,0.274944,-0.732011,0.076587,-0.636016,-0.399875,-0.244395,-0.537697,-0.393709,-0.311142,-0.238212,0.495320,-0.594200,-0.374452,-0.596615
1,-1.471169,-0.732011,-1.019522,-1.123272,0.798001,0.920414,0.935961,-0.393709,-0.311142,-0.238212,0.495320,-0.601050,0.397009,-0.596615
2,0.464448,1.366100,-0.045203,0.060064,0.199063,0.920414,-0.537697,-0.393709,-0.311142,-0.238212,0.495320,0.058145,-0.460169,-0.596615
3,0.916092,-0.732011,0.076587,-0.636016,-0.399875,-0.244395,0.935961,-0.393709,-0.311142,-0.238212,-2.018898,-0.594200,-0.374452,1.163467
4,-0.248930,-0.732011,-0.045203,1.452224,-0.399875,0.920414,-0.537697,-0.393709,-0.311142,-0.238212,0.495320,1.267815,-1.317347,-0.596615

In [99]:
X_train.columns

Index(['age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol',
       'gluc', 'smoke', 'alco', 'active', 'bmi', 'pulse_pressure',
       'lifestyle_risk'],
      dtype='object')

**Random Forest**

In [100]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

In [101]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.70      0.72      0.71      6940
           1       0.71      0.69      0.70      6795

    accuracy                           0.70     13735
   macro avg       0.70      0.70      0.70     13735
weighted avg       0.70      0.70      0.70     13735

**Logistic Regression**

In [103]:
from sklearn.linear_model import LogisticRegression

log_model = LogisticRegression(random_state=42, max_iter=1000)

log_model.fit(X_train, y_train)

y_pred_log = log_model.predict(X_test)

In [104]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_log))

              precision    recall  f1-score   support

           0       0.70      0.79      0.74      6940
           1       0.75      0.66      0.70      6795

    accuracy                           0.72     13735
   macro avg       0.73      0.72      0.72     13735
weighted avg       0.73      0.72      0.72     13735

In [105]:
import pandas as pd

importance = pd.Series(model.feature_importances_, index=X_train.columns)
importance.sort_values(ascending=False)

age               0.255916
bmi               0.158486
weight            0.117162
ap_hi             0.114950
height            0.111728
ap_lo             0.072784
pulse_pressure    0.066855
cholesterol       0.037809
gluc              0.016788
gender            0.016134
lifestyle_risk    0.012093
active            0.008811
smoke             0.005802
alco              0.004683
dtype: float64