<a href="https://colab.research.google.com/github/SaimNaveed646/CardiovasularDiseasePrediction/blob/main/CardioDiseasePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("https://raw.githubusercontent.com/SaimNaveed646/CardiovasularDiseasePrediction/main/cardio_train.csv", sep=";", header=0)

In [3]:
data.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [4]:
data.shape

(70000, 13)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70000 entries, 0 to 69999
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           70000 non-null  int64
 1   age          70000 non-null  int64
 2   gender       70000 non-null  int64
 3   height       70000 non-null  int64
 4   weight       70000 non-null  float64
 5   ap_hi        70000 non-null  int64
 6   ap_lo        70000 non-null  int64
 7   cholesterol  70000 non-null  int64
 8   gluc         70000 non-null  int64
 9   smoke        70000 non-null  int64
 10  alco         70000 non-null  int64
 11  active       70000 non-null  int64
 12  cardio       70000 non-null  int64
dtypes: float64(1), int64(12)
memory usage: 6.9 MB

In [6]:
data.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,19468.865814,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,2467.251667,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,10798.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,17664.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,19703.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,21327.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

# **Cleaning**

In [7]:
data['id'].duplicated().sum()

np.int64(0)

In [8]:
data.isnull().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [9]:
data['age'] = data['age'] / 365

In [10]:
data['height'] = data['height'] / 100

In [11]:
data = data[
    (data['ap_hi'] >= 50) &
    (data['ap_hi'] <= 250) &
    (data['ap_lo'] >= 40) &
    (data['ap_lo'] <= 200) &
    (data['ap_hi'] > data['ap_lo'])
]

In [12]:
data.shape

(68672, 13)

# **Feature Engneering**

In [13]:
cols_to_drop = ["id"]
data = data.drop(columns=cols_to_drop)

In [14]:
X = data.drop("cardio", axis=1)
y = data["cardio"]

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [16]:
import pandas as pd

def preprocess(df):
    df = df.copy()
    df['age'] = df['age'] / 365
    df['bmi'] = df['weight'] / ((df['height']/100) ** 2)
    return df

In [17]:
from sklearn.ensemble import RandomForestClassifier

X_train = preprocess(X_train)

model = RandomForestClassifier(random_state=42)
model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [18]:
import joblib
joblib.dump(model, "rf_model.pkl")

['rf_model.pkl']

In [19]:
# data['bmi'] = data['weight'] / (data['height'] ** 2)

In [20]:
# data['pulse_pressure'] = data['ap_hi'] - data['ap_lo']

In [21]:
# data['lifestyle_risk'] = data['smoke'] + data['alco'] - data['active']

In [22]:
data.head()

,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,50.391781,2,1.68,62.0,110,80,1,1,0,0,1,0
1,55.419178,1,1.56,85.0,140,90,3,1,0,0,1,1
2,51.663014,1,1.65,64.0,130,70,3,1,0,0,0,1
3,48.282192,2,1.69,82.0,150,100,1,1,0,0,1,1
4,47.873973,1,1.56,56.0,100,60,1,1,0,0,0,0

# **Feature Scaling**

In [23]:
# cols_to_drop = ["id"]

# df_model1 = data.drop(columns=cols_to_drop)

In [24]:
# X = df_model1.drop("cardio", axis=1)
# y = df_model1["cardio"]

In [25]:
# from sklearn.model_selection import train_test_split

# X_train, X_test, y_train, y_test = train_test_split(
#     X, y, test_size=0.2, random_state=42, stratify=y
# )

In [26]:
# from sklearn.preprocessing import StandardScaler

# scaler = StandardScaler()
# X_train = scaler.fit_transform(X_train)
# X_test = scaler.transform(X_test)

In [27]:
# import pandas as pd

# X_train = pd.DataFrame(X_train, columns=X.columns)
# X_test = pd.DataFrame(X_test, columns=X.columns)

In [28]:
# X_train.head()

In [29]:
# X_train.columns

**Random Forest**

In [30]:
# from sklearn.ensemble import RandomForestClassifier

# model = RandomForestClassifier(random_state=42)
# model.fit(X_train, y_train)

# y_pred = model.predict(X_test)

In [31]:
# from sklearn.metrics import classification_report

# print(classification_report(y_test, y_pred))

**Logistic Regression**

In [32]:
# from sklearn.linear_model import LogisticRegression

# log_model = LogisticRegression(random_state=42, max_iter=1000)

# log_model.fit(X_train, y_train)

# y_pred_log = log_model.predict(X_test)

In [33]:
# from sklearn.metrics import classification_report

# print(classification_report(y_test, y_pred_log))

In [34]:
# import pandas as pd

# importance = pd.Series(model.feature_importances_, index=X_train.columns)
# importance.sort_values(ascending=False)